name: QualityChecks
on:
  workflow_call:
    secrets:
#      SONAR_TOKEN:
#        required: true

jobs:
  code-quality:
    permissions:
      packages: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of SonarCloud analysis
      - name: validate github workflow files to have pinned versions
        uses: digitalservicebund/github-actions/github-actions-linter@5009471245d84903ea1af84104eb1908f8e2b2a2
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm
      - name: Cache npm dependencies
        id: cache-npm-deps
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        if: steps.cache-npm-deps.outputs.cache-hit != 'true'
        run: npm ci
      - run: |
          npm run typecheck
          npm run style:check

#      - name: SonarCloud Scan
#        if: ${{ github.actor != 'dependabot[bot]' && matrix.npmCMD == 'test:coverage' }}
#        uses: SonarSource/sonarcloud-github-action@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
